### ISSUE TITLE
Python throwing error while training the model

### ISSUE THREAD

**Issue by sprateek007** [federico-terzi/gesture-keyboard#1]
When I try to train model using command

`python learn.py
`
Python throws below error.

```
Prateek-Mac:gesture-keyboard-master Prateek$ python learn.py 
Loading the dataset from 'data'...
Traceback (most recent call last):
  File "learn.py", line 56, in <module>
    number = ord(category) - ord("a")
TypeError: ord() expected a character, but string of length 0 found
```

**Comment by federico-terzi** [comment]
I've experienced that error. It happens when you copy the dataset to some types of file systems and the "space" char gets removed in the file name.
I will solve this problem in the next release, but in the meanwhile you can solve it in this way:
 
change this line:
`category = name.split("_")[0]`


with this line:
```
category = name.split("_")[0]
if category=="":
    category = " "
```

You just tell the program to replace the void character with a space.
That should work.
