### ISSUE TITLE
permissionError(13, Access is Denied, none, 5

### ISSUE THREAD

**Issue by ankita219819** [federico-terzi/gesture-keyboard#24]
My python program shows an error as PermissionError(13, 'access is denied', none, 5), and is unable to find the port. I have run the code on anaconda prompt as "Run as administrator", still shows the same error. any alternative solution for the given problem?
![Untitled](https://user-images.githubusercontent.com/49222160/55453443-9108c700-55f9-11e9-8339-164cce912da2.png)

**Comment by federico-terzi** [comment]
Never happened to me, I'm sorry. Google is your friend

**Comment by ankita219819** [comment]
> Never happened to me, I'm sorry. Google is your friend

google suggested me to ask you about it. anyways thank you so much for the respond.

**Comment by manj9501** [comment]
I wonder if you got the COM port right!

**Comment by ankita219819** [comment]
Can anyone tell me the sequence of execution of module?
Where do we train and where does the process of writing a letter starts?
I m bit confuse about it

**Comment by manj9501** [comment]
The process of training starts after one is certain that the connections between the accelerometer and Arduino and the Bluetooth module are correct and the serial data produced by the Arduino (i.e. raw data from accelerometer) is being received in the proper format into the computer. Are you sure you're successfully done with this step?

**Comment by ankita219819** [comment]
what does the line 217 and 218 in "start.py" means? when does this condition get executed?
please explain in detail.
![image](https://user-images.githubusercontent.com/49222160/56047421-fdef3000-5d62-11e9-9ad7-c0669c4236d5.png)

**Comment by manj9501** [comment]
If we take a look at the corresponding if-condition to the else-condition of line 217, it makes sure that a file in the '.../data' folder is created  only if some data has been recieved from the selected COM port. In case this is not so, i.e. if no data has been received, the body of the else-condition of line 217, is executed, which as you can see, does nothing but prints "ERROR..." to the console.

**Comment by ankita219819** [comment]
Can anyone please tell me how to train and how do we run start.py for prediction (I mean what argument has to be passed to the compiler)

**Comment by ankita219819** [comment]
And then how do we test the gesture

**Comment by manj9501** [comment]
1) Look, after you are positive you're receiving data from your desired COM port, either USB or Bluetooth, you gotta open the **start.py** script, which you need to edit at **line 57** and specify the COM port you are using. 
2) Once that's done, you gotta have the Python(x,y) installed. 
3) Now go to the directory where all the files of this library are stored(let's call it **root**) and empty the contents of the **root/data** folder. 
4) Come back to the **root** directory and open a **Command Window** by pressing and holding down `Shift` while right clicking in the File Explorer window. 
5) Now type `python start.py target=a:0` in the just opened Command Window, to start the collection of sample data for character **a**.
6) If all the previous steps were successful, you should see a log in the Command Window, indicating the successful opening of the correct COM port. 
7) After that, each time you press and hold the recording button, the script will begin recording and storing the readings from the hardware setup as `.txt` files in the **root/data** folder and you'll see a log in the Command Window that the recording is going on, till the recording button is not released.
8) When the recording button is released and pressed again, the next sample for character **a** will be stored and so on.
9) After enough samples for one character have been recorded, press `Ctrl+C`, for stopping the recording process. Check whether **root/data** folder has the recordings.
Attempt the above procedure for now and intimate me ASAP about the success/failure, so that we can move onto the next steps or go through these again.

**Comment by ankita219819** [comment]
yes, I m done with recording a single sample. Can you tell me the next step? @manj9501

**Comment by manj9501** [comment]
When you say 'done with recording a single sample', I really hope you mean you've recorded at least ten samples of a single character, like say **a**, since you'd require at least that many samples of each character for the training algorithm to work upon, to create an accurate model, which would be eventually used for prediction.
10. But recording samples for a single character won't cut it, for if you only record samples for just one character and start the training process, it'd be more or less of a formality. So what you need next is sample data for at least two characters (say **a** and **b** and whatever) for the prediction algorithm to differentiate between. 
11. After that's done, you should execute the following command in the Command Window you opened previously in step 4:
`python learn.py`
This **learn.py** script is where all the functions related to SVM, which is the ML algorithm responsible for the preparation of the prediction model here , are invoked.
12. After training process is done, you need to execute the following command:
`python start.py predict`
to load the model and start predicting the characters according to the gestures.
Predicting is quite similar to the recording process. When you wish to enter a gesture for prediction, you press and hold the recording button and make the respective gesture and release the button when you're done. 
13. If everything goes according to the plan, you'll be shown the correct prediction corresponding to the gesture you made. To stop the prediction process, as you may already know, use `Ctrl+C`
Stick to the above steps, and report back if you run into any issues.

**Comment by ankita219819** [comment]
I have trained for character "1" with 12 recordings, I have a doubt. In learn.py, I have the loop as shown below
              for path, subdirs, files in os.walk(root):
        for name in files:
            #Get the filename
            filename = os.path.join(path, name)
            #Load the sample from file
            sample = signals.Sample.load_from_file(filename)
            #Linearize the sample and then add it to the x_data list
            x_data.append(sample.get_linearized())
            #Extract the category from the file name
            #For example, the file "a_sample_0.txt" will be considered as "a"
            category = name.split("_")[0]
            #Get a number for the category, as an offset from the category
            #to the a char in Ascii
            number = ord(category) - ord("1")
            #Add the category to the y_data list
            y_data.append(number)
            #Include the category and the corresponding number into a dictionary
            #for easy access and referencing
            classes[number] = category


y_data=[0,0,0,0,0,...]
according to the above code category will have only 1 as a value at every loop and ord(category)-ord("1") will always give zero and that is what we are appending to y_data[].
which is throwing me an error while executing clf.fit(x_data, y_data) as "number of classes has to be greater than 1, got 1.

**Comment by manj9501** [comment]
Could you please attach a screenshot, wherein the above error has occurred?

**Comment by ankita219819** [comment]
do I need to keep the value under ord() as 1 even for the next input, say I train for "2" so do I have to change the value here?
`number = ord(category) - ord("1")`

**Comment by ankita219819** [comment]
my predict is working fine. can u tell me the next step?

**Comment by manj9501** [comment]
What exactly would you like to do next?

**Comment by ankita219819** [comment]
what does window.py used for
how do I get my gesture on a python GUI as used in a window using tkinter module

**Comment by manj9501** [comment]
You could use
`python start.py write noautocorrect`

**Comment by ankita219819** [comment]
how can I see the character printed simultaneously as the gesture is made by us like shown in this video https://www.youtube.com/watch?v=OjTNS2ZKqRc

**Comment by manj9501** [comment]
I believe it's solely a matter of how fast you can make one gesture and release the button and press and hold it again for sending the next gesture. In the video, if you look closely, the creator is pretty comfortable with his setup and that's why he, so swiftly, presses the button, holds it down, sends the gesture, releases the button and moves onto the next character.

**Comment by ankita219819** [comment]
I just wanted that our gesture gets simultaneously printed on the GUI.
to get the output on GUI, I have to run window.py separately, where it fetches all character together as a sentence only after the recognized gesture get stored in output.txt and show it on GUI. and my intention is, as soon I press the button for the first gesture, it should get reflected in GUI and as I release it stop and as I again press it reflects the next character on GUI.

**Comment by manj9501** [comment]
Here's what you should do:
1) Open two Command Windows in the **root** folder. 
2) Firstly, in one Command Window(CW), start the prediction, though don't send any data yet.
3) Afterwards, run the window.py script in the other CW.
4) Once the GUI window opens, start sending the gestures and you shall see the characters appearing in the GUI window as soon as they get predicted.

**Comment by ankita219819** [comment]
thank you so much for help. for every doubt u cleared to me as fast as possible, thank you so much for everything.

**Comment by manj9501** [comment]
**Help will always be given at Github to those who ask for it.**
Anyway, I've done a lot of research as far as this project is concerned, so could always use that expertise to help a fellow engineer. At least it's better than sitting idle all day long.
And yeah, you're welcome (: 

PS: Don't be surprised, the 'engineer' bit is just an assumption lol

**Comment by ankita219819** [comment]
can u  tell me how to provide space using this device? @manj9501

**Comment by manj9501** [comment]
1. Open **start.py** in any source code editor of your like (Notepad++, maybe).
2. At line 206, you shall see some code pertaining to the deletion of the last character. 
The code here is faulty to some extent since it doesn't take into account, a phenomenon which Microsoft calls **prettying the path**. This is related to Windows ignoring the case (UPPER, lower, etc.) you are using to name your files and folders. And though this can be disabled through some changes in the Registry, we'll focus rather on a workaround.
3. In place of lines 206-207, paste the following snippet and save the changes:
```
if char == '~': #Delete the last character
	sentence = sentence[:-1]
elif char == '`': #Adds space
	sentence += " "
```
4. In order to record the gesture for deleting the last character, execute the following command in the CW:
`python start.py target=~:0`
To keep things simple, ape the creator, and use a horizontal swipe from right to left as the gesture, 
5. Likewise, for adding the space gesture, use
`python start.py target=`:0`
Again, use a horizontal swipe from left to right for simplicity.
6. After recording both the samples, train the model as usual, and verify if you can successfully add spaces and delete characters.
Note that you'll have to sacrifice some special characters for the _Space_ and the _Delete_ gestures. Use some other special character to include the  _Delete All Characters_ feature as well.

**Comment by ankita219819** [comment]
whenever I m doing as `python start.py target:0` and train them it shows some problem as value error

**Comment by manj9501** [comment]
`python start.py target:0`
What exactly are you intending to do when you use the above statement? Since this statement is completely erroneous.

**Comment by ankita219819** [comment]
the above code is to train the _space_

**Comment by manj9501** [comment]
Did I instruct you to use 
`python start.py target:0`?

**Comment by ankita219819** [comment]
I think so

**Comment by manj9501** [comment]
Oops, my bad! 
Use **python start.py target=`:0**

**Comment by manj9501** [comment]
Mind closing the issue? And maybe stopping by for a quick chat?

**Comment by shafirayulia** [comment]
Sir, can you help me to solve this, I can't run 'learn.py' :( something wrong at line 56, number=ord(category)-ord("a")
![Screenshot (578)](https://user-images.githubusercontent.com/25631903/62843561-e6aa5a00-bce4-11e9-9e7e-eecc2abc338e.png)

**Comment by shafirayulia** [comment]
Sir, can you help me, i just got blank in my Tkinter, it shows nothing :(
![Screenshot (579)](https://user-images.githubusercontent.com/25631903/62845666-1876ed00-bcf4-11e9-928e-91920d707226.png)

**Comment by manj9501** [comment]
@ankita219819 Mind closing the issue?

**Comment by ankita219819** [comment]
> @ankita219819 Mind closing the issue?

Yes I'm closing it now
